export const serviceData = [
  {
    slug: 'civil-works',
    title: 'Civil Works',
    short: 'Structural and general civil execution support.',
    description: 'OKG Contracting supports project teams with disciplined civil works execution, site coordination and documented progress control.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85',
    scope: ['General civil works support', 'Foundations and structural workfront assistance', 'Site preparation coordination', 'Workforce and daily output monitoring'],
    process: ['Review drawings, BOQ and site access', 'Plan manpower and supervision requirements', 'Mobilise site team and agree reporting format', 'Track daily progress, inspections and handover items'],
    quality: ['Supervisor checks', 'Inspection readiness', 'Progress photo records', 'Clear escalation for delays or site constraints'],
    suitable: ['Residential buildings', 'Commercial projects', 'Industrial facilities', 'Main contractor work packages'],
  },
  {
    slug: 'plastering-gypsum',
    title: 'Plastering and Gypsum Works',
    short: 'Rush coat, plaster application, gypsum works and finishing.',
    description: 'Professional plastering and gypsum work support with attention to surface preparation, alignment and finishing standards.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',
    scope: ['Rush coat and plaster application', 'Internal and external plastering', 'Gypsum board coordination', 'Finishing preparation and snag support'],
    process: ['Confirm areas and substrate condition', 'Mobilise plastering team and materials', 'Execute by zone with supervisor checks', 'Support inspection and finishing handover'],
    quality: ['Surface alignment checks', 'Thickness and finish monitoring', 'Mock-up or sample review where required', 'Snag list closure support'],
    suitable: ['Villas and apartments', 'Commercial interiors', 'Renovation works', 'Finishing work packages'],
  },
  {
    slug: 'masonry-blockwork',
    title: 'Masonry and Blockwork',
    short: 'Block laying, alignment and coordinated progress delivery.',
    description: 'Blockwork and masonry execution support delivered through organised manpower, clear workfront control and supervisor-led progress reporting.',
    image: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?auto=format&fit=crop&w=1200&q=85',
    scope: ['Block laying and masonry support', 'Alignment and level coordination', 'Openings and workfront sequencing', 'Progress monitoring by area'],
    process: ['Review layout and work areas', 'Assign masons and helpers by zone', 'Coordinate daily production targets', 'Prepare work for inspection and follow-up'],
    quality: ['Line and level checks', 'Opening coordination', 'Daily supervisor review', 'Photo documentation'],
    suitable: ['Residential buildings', 'Commercial projects', 'Boundary walls', 'Partition and blockwork packages'],
  },
  {
    slug: 'concrete-works',
    title: 'Concrete Works',
    short: 'Casting, finishing and curing support.',
    description: 'Concrete works support for controlled casting, finishing, curing assistance and coordination with project supervision teams.',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=85',
    scope: ['Concrete casting support', 'Finishing and surface work assistance', 'Curing coordination', 'Labour and supervision support'],
    process: ['Confirm pour area and readiness', 'Mobilise labour and tools', 'Support casting and finishing activities', 'Document completion and curing requirements'],
    quality: ['Pre-pour readiness checks', 'Supervisor monitoring', 'Curing follow-up', 'Inspection and completion records'],
    suitable: ['Building slabs', 'Foundations', 'External works', 'Repair and maintenance packages'],
  },
  {
    slug: 'steel-shuttering',
    title: 'Steel and Shuttering',
    short: 'Rebar preparation, shuttering support and execution coordination.',
    description: 'Steel fixing and shuttering support focused on safe coordination, proper sequencing and inspection readiness.',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85',
    scope: ['Steel fixing support', 'Shuttering assistance', 'Workfront sequencing', 'Inspection preparation'],
    process: ['Review drawings and work areas', 'Assign trade-specific workforce', 'Coordinate completion by zone', 'Support inspection and corrections'],
    quality: ['Drawing coordination', 'Supervisor checks', 'Inspection status tracking', 'Issue escalation'],
    suitable: ['Structural packages', 'Concrete preparation works', 'Main contractor support', 'Civil work packages'],
  },
  {
    slug: 'skilled-workforce',
    title: 'Skilled Workforce Deployment',
    short: 'Masons, helpers and trade-specific workforce mobilisation.',
    description: 'Reliable deployment of skilled and semi-skilled construction manpower with attendance tracking and daily productivity monitoring.',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=85',
    scope: ['Masons and helpers', 'Trade-specific deployment', 'Daily attendance coordination', 'Supervisor-led productivity control'],
    process: ['Confirm manpower requirements', 'Assign suitable workforce', 'Track attendance and deployment', 'Report productivity and site issues'],
    quality: ['Worker suitability review', 'Daily attendance records', 'Supervisor feedback', 'Replacement coordination where required'],
    suitable: ['Fast mobilisation needs', 'Main contractor support', 'Finishing packages', 'Civil works support'],
  },
  {
    slug: 'site-supervision',
    title: 'Site Supervision',
    short: 'Daily monitoring, workforce productivity control and escalation reporting.',
    description: 'Site supervision support to monitor work progress, coordinate manpower, escalate issues and maintain clear communication with project teams.',
    image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85',
    scope: ['Daily site monitoring', 'Workforce coordination', 'Progress and issue reporting', 'Escalation support'],
    process: ['Agree supervision scope', 'Monitor daily output', 'Record site constraints and progress', 'Coordinate corrective action'],
    quality: ['Daily reports', 'Progress photos', 'Issue logs', 'Inspection follow-up'],
    suitable: ['Active construction sites', 'Subcontractor packages', 'Workforce-heavy projects', 'Time-sensitive workfronts'],
  },
  {
    slug: 'documentation-control',
    title: 'Documentation Control',
    short: 'Progress reports, approvals, inspection records and handover support.',
    description: 'Construction documentation support for progress visibility, inspection tracking, approvals and professional handover records.',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=85',
    scope: ['Daily progress reports', 'Inspection records', 'Approval tracking', 'Handover documentation support'],
    process: ['Define required records', 'Collect site updates and photos', 'Track approvals and open items', 'Prepare handover documentation'],
    quality: ['Document completeness checks', 'Photo records', 'Approval status tracking', 'Clear version control'],
    suitable: ['Managed work packages', 'Client reporting', 'Inspection workflows', 'Project closeout'],
  },
];

export const qhseItems = ['Quality control', 'Daily supervision', 'Toolbox talks', 'PPE compliance', 'Inspection workflow', 'Incident reporting', 'Environmental responsibility', 'Health and safety policy'];

export const capabilityItems = [
  'Workforce mobilisation', 'Civil works execution', 'Finishing works', 'Daily site supervision',
  'Productivity tracking', 'Project reporting', 'Inspection tracking', 'Material coordination',
  'Workforce attendance', 'Subcontractor coordination', 'Documentation control', 'QHSE monitoring',
  'Client communication', 'Escalation procedures'
];