import {
  BarChart3,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardList,
  FileArchive,
  FileSpreadsheet,
  FileText,
  FolderKanban,
  HardHat,
  Image,
  LayoutDashboard,
  ReceiptText,
  Search,
  Settings,
  ShieldCheck,
  Users,
} from 'lucide-react';

export const adminModules = [
  { key: 'dashboard', label: 'Dashboard', path: '/admin/dashboard', Icon: LayoutDashboard },
  { key: 'enquiries', label: 'Enquiries', path: '/admin/contact-submissions', Icon: FileText },
  { key: 'clients', label: 'Client CRM', path: '/admin/clients', Icon: Users },
  { key: 'projects', label: 'Projects', path: '/admin/projects', Icon: FolderKanban },
  { key: 'quotations', label: 'Quotations', path: '/admin/quotations', Icon: ClipboardList },
  { key: 'invoices', label: 'Invoices', path: '/admin/invoices', Icon: ReceiptText },
  { key: 'documents', label: 'Documents', path: '/admin/documents', Icon: FileArchive },
  { key: 'attendance', label: 'Labour Attendance', path: '/admin/attendance', Icon: HardHat },
  { key: 'boq', label: 'BOQ / Measurements', path: '/admin/boq', Icon: FileSpreadsheet },
  { key: 'photos', label: 'Progress Photos', path: '/admin/photos', Icon: Image },
  { key: 'tasks', label: 'Tasks', path: '/admin/tasks', Icon: CalendarDays },
  { key: 'reports', label: 'Reports', path: '/admin/reports', Icon: BarChart3 },
  { key: 'roles', label: 'Roles', path: '/admin/roles', Icon: ShieldCheck },
  { key: 'notifications', label: 'Notifications', path: '/admin/notifications', Icon: Bell },
  { key: 'settings', label: 'Settings', path: '/admin/settings', Icon: Settings },
  { key: 'cms', label: 'Website CMS', path: '/admin/cms', Icon: BriefcaseBusiness },
  { key: 'seo', label: 'SEO Panel', path: '/admin/seo', Icon: Search },
];